[profile.default]
libs = ['../../node_modules']
remappings=[
    "openzeppelin-contracts/=node_modules/@openzeppelin/",
    "aave-v3-origin/=node_modules/@aave-dao/aave-v3-origin/src/",
    "solidity-utils/=node_modules/@bgd-labs/solidity-utils/src/"
]
